version: '3.8'

services:
  app:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - db

  db:
    image: keinos/sqlite3:latest
    volumes:
      - ./data:/data
    environment:
      - SQLITE_DATABASE=/data/bookstore.db